platform :ios, '7.0' 
pod 'AFNetworking', '~> 2.5.3'
pod 'SDWebImage', '~> 3.7.1'
pod 'FMDB', '~> 2.3'
pod 'RegexKitLite', '~> 4.0'
pod 'MJRefresh', '~> 1.4.6'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJExtension', '~> 2.1.0'
pod 'RDVTabBarController', '~> 1.1.9'
pod 'PPRevealSideViewController', '~> 1.2.0'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.1'
pod 'Reachability', '~> 3.2'
pod 'Masonry', '~> 0.6.1'